Add CMakelist and .travis
ARMmbed/mbed-os-example-cpu-stats pull request #69
Opened 2020-11-12 16:41 UTC by rajkan01

Adding CMakelists to our examples

@0xc0170

2020-11-16 13:43 UTC, 0xc0170 requested changes

2020-11-16 13:43 UTC, 0xc0170 commented on CMakeLists.txt
> +        mbed-events
events should be part of Mbed OS target

2020-11-16 13:48 UTC, 0xc0170 approved these changes

2020-11-17 10:37 UTC, hugueskamba reviewed
How about updating the Mbed OS reference in the lib file?

2020-11-18 10:34 UTC, hugueskamba approved these changes

2020-11-20 11:05 UTC, merged